[bell]
animation = "EaseOutExpo"

[font]
builtin_box_drawing = true
size = 16.0

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[font.italic]
family = "BerkeleyMono Nerd Font"
style = "Italic"

[font.bold]
family = "BerkeleyMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BerkeleyMono Nerd Font"
style = "Bold Italic"

[window]
option_as_alt = "Both"
dynamic_title = true
padding = { x = 8, y = 8 }

[window.dimensions]
columns = 150
lines = 45
