[bell]
animation = "EaseOutExpo"

[font]
builtin_box_drawing = true
size = 16.0

[font.normal]
family = "OperatorMonoSSmLig Nerd Font"
style = "Light"

[window]
option_as_alt = "Both"
dynamic_title = true
decorations = "None"
padding = { x = 8, y = 8 }

[window.dimensions]
columns = 120
lines = 48
