[bell]
animation = "EaseOutExpo"

[font]
builtin_box_drawing = true
size = 16.0

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"
dynamic_title = true
padding = { x = 8, y = 8 }

[window.dimensions]
columns = 120
lines = 45
